### ISSUE TITLE
wallet not syncing

### ISSUE THREAD

**Issue by crappyrules** [turtlecoin/turtlecoin-webwallet-js#4]
Maybe I missed a step in launching the process or I do not have my daemon configured properly, but when I run this locally on my machine, the wallet height fails to change.  The chain height is correct.  I'm running on debian 9.  I set up a cron for the api as suggested. Maybe @dave can hit me up with some direction?

**Comment by crappyrules** [comment]
Maybe I did not set the cron up properly?  I used the readme in the php_api_src folder
```fail: BlockchainChache[0]
         at WebWallet.Helpers.BlockchainCache.BuildCache(PerformContext context) in ~/turtlecoin/trtlww/Helpers/BlockchainCache.cs:line 117
warn: BlockchainChache[0]
      Potentially missing transactions at height 129599, expected min 50, found 49
```

**Comment by plenteum** [comment]
Hi, that's a validation step I added to double check that it was adding at the least the minimum transactions as it cycles through the blocks to cache them in the background. If it's missing txs as it caches, there could be a number of reasons for that - I will have another look and see if I can pinpoint what's causing that and will need to add a few more steps to re-add the missing txs.

To clarify, the old_php_api is the original implementation from masari which I have modified to work with the turtle transaction structure, but is not optimised and not fully tested as we've replaced it with the dot net core background caching process. The php background caching (using the cron job and php files with env var) was left in purely if someone would prefer to use this method in their own fork, but if you do, there are changes required for the front end (to point the ajax calls at the php api) and you also would not need to run the dotNetCore app, you only need the php api, and the contents for the wwwroot folder for the front end. 

Also, note that this is still a work in progress - the sync on turtles network is super slow, due to the volume of transactions it has to download to validate them client side, and I'm trying to see if I can implement a faster initial sync, or pre-sync to first identify the transactions owned by the wallet being sync'd, then fetch the full detail for only those transactions.

**Comment by crappyrules** [comment]
Ok.  I'll look around and see if I can't figure out what is going on here on my local copy.  I know it's seeing the daemon, but it is just not synchronizing the wallet still after 12 hours.  I'm going to guess there is still work to be done on the send tx since I opened the same wallet on your demo site, but cannot seem to transfer out.  Everything looks great though so far.

**Comment by plenteum** [comment]
Hi, you'll only be able to send once the wallet is fully sync'd. 

Are you getting errors in the browser console? 

Fell free to ping me in discord dev_general channel if you want to talk through the issues on your local.

Dave
